version: "3.3"

services:
    web-app:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        image: kidssy/web-app:0.1.0
        ports:
            - 8080:80
        hostname: web-app